#!/bin/bash

#source ./error_handling
source "$(dirname "$BASH_SOURCE")/error_handling"

# Prevent annoying debian error messages
# echo "export LC_ALL=C" >>~/.bashrc

# Update the operating system and all installed SW packages
apt update
apt full-upgrade -y
