#!/bin/bash

#source ./error_handling
source "$(dirname "$BASH_SOURCE")/error_handling"

# Prevent annoying debian error messages
echo "export LC_ALL=C" >>~/.bashrc

source "$(dirname "$BASH_SOURCE")/install"
source "$(dirname "$BASH_SOURCE")/config"

mkdir /data
chown admin:admin /data

source "$(dirname "$BASH_SOURCE")/swap"
